#!/bin/bash

outputPath=$1
cd $outputPath
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -days 36500 -out rootCA.crt \
     -subj "/C=CN/ST=SH/L=SH/O=JiaLiProxy/OU=Section/CN=JiaLiProxy SSL Proxying/emailAddress=JiaLiProxy@JiaLiProxy"
echo "============="
echo $outputPath
echo "rootCA generated at :"
pwd
echo "============="

chmod 666 rootCA.*


exit 0